# Generated by Django 5.2.1 on 2025-05-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aits', '0002_customuser_is_admin_customuser_is_lecturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('lecturer', 'Lecturer'), ('registrar', 'Registrar'), ('student', 'Student')], default='student', max_length=10),
        ),
    ]
